
import com.sun.activation.viewers.ImageViewer;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.reflect.Array;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PERUMAL
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
         Random rand = new Random(); 
        int rand_int1 = rand.nextInt(1000); 
        int rand_int2 = rand.nextInt(1000); 
        int rand_int3 = rand.nextInt(1000); 
        String rdg="",rdg1="",rdg2="";
             rdg=rand_int1+"";
             rdg1=rand_int2+"";
             rdg2=rand_int3+"";
             jTextField2.setText(rdg);
             jTextField3.setText(rdg1);
             jTextField4.setText(rdg2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField4 = new javax.swing.JPasswordField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(1100, 700, 1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER FORM");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 390, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Account No");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 90, 80, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(140, 90, 290, 30);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 500, 80, 30);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(270, 500, 90, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select the Type", "Addition", "Multiplication" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(140, 130, 300, 30);

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField2MouseEntered(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 190, 60, 30);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(240, 240, 60, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(240, 290, 60, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("     Type");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 130, 90, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Level 1");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 190, 80, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Level 2");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 240, 80, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Level 3");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 290, 80, 30);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 190, 50, 30);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(310, 240, 50, 30);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(310, 290, 50, 30);
        jPanel1.add(jPasswordField2);
        jPasswordField2.setBounds(140, 190, 90, 30);
        jPanel1.add(jPasswordField3);
        jPasswordField3.setBounds(140, 240, 90, 30);
        jPanel1.add(jPasswordField4);
        jPasswordField4.setBounds(140, 290, 90, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(370, 190, 60, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(370, 240, 60, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(370, 290, 60, 30);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(580, 230, 50, 30);
        jPanel1.add(jLabel12);
        jLabel12.setBounds(630, 280, 0, 30);
        jPanel1.add(jLabel13);
        jLabel13.setBounds(580, 280, 50, 30);
        jPanel1.add(jLabel15);
        jLabel15.setBounds(630, 330, 0, 30);

        jLabel11.setText("     ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(580, 330, 50, 30);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8);
        jTextField8.setBounds(140, 340, 220, 30);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Email");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 340, 70, 30);

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jButton3.setText("Photo Chooser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(320, 380, 110, 30);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(140, 380, 170, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Photo");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 380, 60, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("Question");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(40, 430, 60, 20);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("Answer");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(40, 464, 60, 20);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(140, 420, 300, 30);
        jPanel1.add(jTextField11);
        jTextField11.setBounds(140, 460, 300, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(610, 90, 470, 540);

        jLabel17.setBackground(new java.awt.Color(0, 204, 204));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 153));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("BIOMETRIC TEMPLATE PROTECTION ");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 20, 1040, 50);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rgs.gif"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel18.setMaximumSize(new java.awt.Dimension(1000, 524));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 90, 560, 540);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:

        Random objGenerator2 = new Random();
        String rdg="",rdg1="",rdg2="";

        int randomNumber2 = objGenerator2.nextInt(100);
        rdg2=randomNumber2+"";

        jTextField4.setText(rdg2);
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped

        String str = jTextField2.getText();

        if((jTextField3.getText().length()<0)&&(jTextField4.getText().length()<0)){
            JOptionPane.showMessageDialog(null,"enter all character");
        }else if((jTextField3.getText().length()==3)&&(jTextField4.getText().length()==3)){

        }

    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        Random objGenerator = new Random();

        String rdg="",rdg1="",rdg2="";
        int randomNumber = objGenerator.nextInt(100);
        rdg=randomNumber+"";

        jTextField2.setText(rdg);

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField2MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            int bn=0;
//             String newDir = "new_dir";
//        boolean success = (new File(newDir)).mkdir();
//
//        if (success) {
//            System.out.println("Successfully created directory: " + newDir);
//        } else {
//            System.out.println("Failed to create directory: " + newDir);
//        }
//
//        // Create a directory; all non-existent ancestor directories are
//        // automatically created.
//        newDir = "C:\\Users\\WINDOWS 10\\Documents\\NetBeansProjects\\BlockChainVoting\\web\\photo";
//        success = (new File(newDir)).mkdirs();
//
//        if (success) {
//            System.out.println("Successfully created directory: " + newDir);
//        } else {
//            System.out.println("Failed to create directory: " + newDir);
//        }

                  InputStream inStream = null;
	OutputStream outStream = null;

 
    	    File afile =new File(jTextField9.getText());
            System.out.println(afile);
       
    	    File bfile =new File(jTextField1.getText()+".jpg");

    	    inStream = new FileInputStream(afile);
    	    outStream = new FileOutputStream(bfile);
 
    	    byte[] buffer = new byte[1024];
 
    	    int length;
    	    //copy the file content in bytes 
    	    while ((length = inStream.read(buffer)) > 0){
 
    	    	outStream.write(buffer, 0, length);
 
    	    }
 
    	    inStream.close();
    	    outStream.close();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/security","root","root");
            Statement st=con.createStatement();
            Statement ob=con.createStatement();
            int s10 = 0, s11 = 0, s12 = 0,  cal11 = 0, cal12 = 0, cal13 = 0;
            int mul1=1,mul2=1,mul3=1;
            String v111="",v112="",v113="";
            String text11 = jTextField2.getText();
            String text12 = jTextField3.getText();
            String text13 = jTextField4.getText();
            int[] ar = new int[text11.length()];
            int[] ar1 = new int[text12.length()];
            int[] ar2 = new int[text13.length()];
            System.out.println(text11);
            System.out.println(text12);
            System.out.println(text13);
           
            if (jComboBox1.getSelectedItem().toString().equals("Addition")) {
                char[] ch1 = new char[text11.length()];
                for (int i = 0; i < text11.length(); i++) {
                    ch1[i] = text11.charAt(i);
                }
                for (char c1 : ch1) {
                    System.out.println(c1);
                    s10 = Character.getNumericValue(c1);
                    System.out.println("Text10 :" + s10);
                    cal11 = cal11 + s10;
                    System.out.println("Text3  cal1 :" + cal11);
                }
                char[] ch2 = new char[text12.length()];
                // Copy character by character into array
                for (int i1 = 0; i1 < text12.length(); i1++) {
                    ch2[i1] = text12.charAt(i1);
                }

                // Printing content of array
                for (char c2 : ch2) {
                    System.out.println(c2);
                    s11 = Character.getNumericValue(c2);
                    System.out.println("Text12 :" + s11);
                    cal12 = cal12 + s11;
                    System.out.println("Text13  cal12 :" + cal12);
                }

                char[] ch3 = new char[text13.length()];
                // Copy character by character into array
                for (int i2 = 0; i2 < text13.length(); i2++) {
                    ch3[i2] = text13.charAt(i2);
                }

                // Printing content of array
                for (char c3 : ch3) {
                    System.out.println(c3);
                    s12 = Character.getNumericValue(c3);
                    System.out.println("Text13 :" + s12);
                    cal13 = cal13 + s12;
                    System.out.println("Text3  cal13 :" + cal13);
                }

                v111 = cal11 + ""; v112 = cal12 + ""; v113 = cal13 + "";
                jLabel8.setText(v111);
                jLabel9.setText(v112);
                jLabel10.setText(v113);
            }else if (jComboBox1.getSelectedItem().toString().equals("Multiplication")) {
                  char[] ch1 = new char[text11.length()];
                for (int i = 0; i < text11.length(); i++) {
                    ch1[i] = text11.charAt(i);
                }
                for (char c1 : ch1) {
                    System.out.println(c1);
                    s10 = Character.getNumericValue(c1);
                    System.out.println("Text10 :" + s10);
                    cal11 = cal11 + s10;
                    System.out.println("Text3  cal1 :" + cal11);
                }
                char[] ch2 = new char[text12.length()];
                // Copy character by character into array
                for (int i1 = 0; i1 < text12.length(); i1++) {
                    ch2[i1] = text12.charAt(i1);
                }

                // Printing content of array
                for (char c2 : ch2) {
                    System.out.println(c2);
                    s11 = Character.getNumericValue(c2);
                    System.out.println("Text12 :" + s11);
                    cal12 = cal12 + s11;
                    System.out.println("Text13  cal12 :" + cal12);
                }

                char[] ch3 = new char[text13.length()];
                // Copy character by character into array
                for (int i2 = 0; i2 < text13.length(); i2++) {
                    ch3[i2] = text13.charAt(i2);
                }

                // Printing content of array
                for (char c3 : ch3) {
                    System.out.println(c3);
                    s12 = Character.getNumericValue(c3);
                    System.out.println("Text13 :" + s12);
                    cal13 = cal13 + s12;
                    System.out.println("Text3  cal13 :" + cal13);
                }

                v111 = cal11 + ""; v112 = cal12 + ""; v113 = cal13 + "";
                jLabel8.setText(v111);
                jLabel9.setText(v112);
                jLabel10.setText(v113);
            }

          
                   int s=0,s1=0,s2=0,cal1=0,cal2=0,cal3=0;
                       String text1=jTextField5.getText();
                       String text2=jTextField6.getText();
                       String text3=jTextField7.getText();
                   Random objGenerator = new Random();
                   String radg="";
                int[] ar10 = new int[text1.length()];
                   int[] ar11 = new int[text2.length()];
                    int[] ar12 = new int[text3.length()];
                    int randomNumber = objGenerator.nextInt(100);
                    radg=randomNumber+"";
                   if(jComboBox1.getSelectedItem().toString().equals("Addition")){
                
                            char[] ch1 = new char[text1.length()];
                          // Copy character by character into array
                        for (int i = 0; i < text1.length(); i++) {
                                ch1[i] = text1.charAt(i); 
                            }
                
                        // Printing content of array
                        for (char c1 : ch1) {
                                System.out.println(c1);
                                if(c1=='A'){
                                        s=1;
                                    }else if(c1=='B'){
                                        s=2;
                                    }else if(c1=='C'){
                                        s=3;
                                    }else if(c1=='D'){
                                        s=4;
                                    }else if(c1=='E'){
                                        s=5;
                                    }else if(c1=='F'){
                                        s=6;
                                    }else if(c1=='G'){
                                        s=7;
                                    }else if(c1=='H'){
                                        s=8;
                                    }else if(c1=='I'){
                                        s=9;
                                    }else if(c1=='J'){
                                        s=10;
                                    }else if(c1=='K'){
                                        s=11;
                                    }else if(c1=='L'){
                                        s=12;
                                    }else if(c1=='M'){
                                        s=13;
                                    }else if(c1=='N'){
                                        s=14;
                                    }else if(c1=='O'){
                                        s=15;
                                    }else if(c1=='P'){
                                        s=16;
                                    }else if(c1=='Q'){
                                        s=17;
                                    }else if(c1=='R'){
                                        s=18;
                                    }else if(c1=='S'){
                                        s=19;
                                    }else if(c1=='T'){
                                        s=20;
                                    }else if(c1=='U'){
                                        s=21;
                                    }else if(c1=='V'){
                                        s=22;
                                    }else if(c1=='W'){
                                        s=23;
                                    }else if(c1=='X'){
                                        s=24;
                                    }else if(c1=='Y'){
                                        s=25;
                                    }else if(c1=='Z'){
                                        s=26;
                                    }else{
                                       s=0;
                                    }
                    System.out.println("s :"+s);
                       cal1=cal1+s;
                       System.out.println("cal1 :"+cal1);
                            }
                            char[] ch2 = new char[text2.length()];
                          // Copy character by character into array
                        for (int i1 = 0; i1 < text2.length(); i1++) {
                                ch2[i1] = text2.charAt(i1);
                            }
                
                        // Printing content of array
                        for (char c2 : ch2) {
                              System.out.println(c2);
                                if(c2=='A'){
                                        s1=1;
                                    }else if(c2=='B'){
                                        s1=2;
                                    }else if(c2=='C'){
                                        s1=3;
                                    }else if(c2=='D'){
                                        s1=4;
                                    }else if(c2=='E'){
                                        s1=5;
                                    }else if(c2=='F'){
                                        s1=6;
                                    }else if(c2=='G'){
                                        s1=7;
                                    }else if(c2=='H'){
                                        s1=8;
                                    }else if(c2=='I'){
                                        s1=9;
                                    }else if(c2=='J'){
                                        s1=10;
                                    }else if(c2=='K'){
                                        s1=11;
                                    }else if(c2=='L'){
                                        s1=12;
                                    }else if(c2=='M'){
                                        s1=13;
                                    }else if(c2=='N'){
                                        s1=14;
                                    }else if(c2=='O'){
                                        s1=15;
                                    }else if(c2=='P'){
                                        s1=16;
                                    }else if(c2=='Q'){
                                        s1=17;
                                    }else if(c2=='R'){
                                        s1=18;
                                    }else if(c2=='S'){
                                        s1=19;
                                    }else if(c2=='T'){
                                        s1=20;
                                    }else if(c2=='U'){
                                        s1=21;
                                    }else if(c2=='V'){
                                        s1=22;
                                    }else if(c2=='W'){
                                        s1=23;
                                    }else if(c2=='X'){
                                        s1=24;
                                    }else if(c2=='Y'){
                                        s1=25;
                                    }else if(c2=='Z'){
                                        s1=26;
                                    }else{
                                       s1=0;
                                    }
                    System.out.println("s1 :"+s1);
                       cal2=cal2+s1;
                          System.out.println("cal2 :"+cal2);
                            }
                        char[] ch3 = new char[text3.length()];
                          // Copy character by character into array
                        for (int i2 = 0; i2 < text3.length(); i2++) {
                                ch3[i2] = text3.charAt(i2);
                            }
                         // Printing content of array
                        for (char c3 : ch3) {
                                System.out.println(c3);
                                if(c3=='A'){
                                        s2=1;
                                    }else if(c3=='B'){
                                        s2=2;
                                    }else if(c3=='C'){
                                        s2=3;
                                    }else if(c3=='D'){
                                        s2=4;
                                    }else if(c3=='E'){
                                        s2=5;
                                    }else if(c3=='F'){
                                        s2=6;
                                    }else if(c3=='G'){
                                        s2=7;
                                    }else if(c3=='H'){
                                        s2=8;
                                    }else if(c3=='I'){
                                        s2=9;
                                    }else if(c3=='J'){
                                        s2=10;
                                    }else if(c3=='K'){
                                        s2=11;
                                    }else if(c3=='L'){
                                        s2=12;
                                    }else if(c3=='M'){
                                        s2=13;
                                    }else if(c3=='N'){
                                        s2=14;
                                    }else if(c3=='O'){
                                        s2=15;
                                    }else if(c3=='P'){
                                        s2=16;
                                    }else if(c3=='Q'){
                                        s2=17;
                                    }else if(c3=='R'){
                                        s2=18;
                                    }else if(c3=='S'){
                                        s2=19;
                                    }else if(c3=='T'){
                                        s2=20;
                                    }else if(c3=='U'){
                                        s2=21;
                                    }else if(c3=='V'){
                                        s2=22;
                                    }else if(c3=='W'){
                                        s2=23;
                                    }else if(c3=='X'){
                                        s2=24;
                                    }else if(c3=='Y'){
                                        s2=25;
                                    }else if(c3=='Z'){
                                        s2=26;
                                    }else{
                                       s2=0;
                                    }
                                System.out.println("s2 :"+s2);
                                cal3=cal3+s2;
                                   System.out.println("cal3 :"+cal3);
                            }
                             String v11=cal1+"",v12=cal2+"",v13=cal3+"";
                       jLabel3.setText(v11);  jLabel13.setText(v12); jLabel15.setText(v13);
                               bn=st.executeUpdate("insert into register values('"+jTextField1.getText()+"','"+jComboBox1.getSelectedItem()+"','"+jPasswordField2.getText()+"','"+jPasswordField3.getText()+"','"+jPasswordField4.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+v111+"','"+v112+"','"+v113+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"','"+v11+"','"+v12+"','"+v13+"','Active','5000','"+jTextField8.getText()+"','"+jTextField10.getText()+"','"+jTextField11.getText()+"','')");
            bn=st.executeUpdate("insert into secure values('"+jTextField1.getText()+"','0','0','0')");
            if(bn==1){
                this.setVisible(false);
                JOptionPane.showMessageDialog(null,"Added Successfully");
                Home rs=new Home();
                rs.setVisible(true);

            }else{
                this.setVisible(true);
                JOptionPane.showMessageDialog(null,"Added Failed");
            }
                       }else if(jComboBox1.getSelectedItem().toString().equals("Multiplication")){
                           char[] ch1 = new char[text1.length()];
                          // Copy character by character into array
                        for (int i = 0; i < text1.length(); i++) {
                                ch1[i] = text1.charAt(i); 
                            }
                
                        // Printing content of array
                        for (char c1 : ch1) {
                                System.out.println(c1);
                                if(c1=='A'){
                                        s=1;
                                    }else if(c1=='B'){
                                        s=2;
                                    }else if(c1=='C'){
                                        s=3;
                                    }else if(c1=='D'){
                                        s=4;
                                    }else if(c1=='E'){
                                        s=5;
                                    }else if(c1=='F'){
                                        s=6;
                                    }else if(c1=='G'){
                                        s=7;
                                    }else if(c1=='H'){
                                        s=8;
                                    }else if(c1=='I'){
                                        s=9;
                                    }else if(c1=='J'){
                                        s=10;
                                    }else if(c1=='K'){
                                        s=11;
                                    }else if(c1=='L'){
                                        s=12;
                                    }else if(c1=='M'){
                                        s=13;
                                    }else if(c1=='N'){
                                        s=14;
                                    }else if(c1=='O'){
                                        s=15;
                                    }else if(c1=='P'){
                                        s=16;
                                    }else if(c1=='Q'){
                                        s=17;
                                    }else if(c1=='R'){
                                        s=18;
                                    }else if(c1=='S'){
                                        s=19;
                                    }else if(c1=='T'){
                                        s=20;
                                    }else if(c1=='U'){
                                        s=21;
                                    }else if(c1=='V'){
                                        s=22;
                                    }else if(c1=='W'){
                                        s=23;
                                    }else if(c1=='X'){
                                        s=24;
                                    }else if(c1=='Y'){
                                        s=25;
                                    }else if(c1=='Z'){
                                        s=26;
                                    }else{
                                       s=0;
                                    }
                    System.out.println("s :"+s);
                       cal1=cal1+s;
                       System.out.println("cal1 :"+cal1);
                            }
                            char[] ch2 = new char[text2.length()];
                          // Copy character by character into array
                        for (int i1 = 0; i1 < text2.length(); i1++) {
                                ch2[i1] = text2.charAt(i1);
                            }
                
                        // Printing content of array
                        for (char c2 : ch2) {
                              System.out.println(c2);
                                if(c2=='A'){
                                        s1=1;
                                    }else if(c2=='B'){
                                        s1=2;
                                    }else if(c2=='C'){
                                        s1=3;
                                    }else if(c2=='D'){
                                        s1=4;
                                    }else if(c2=='E'){
                                        s1=5;
                                    }else if(c2=='F'){
                                        s1=6;
                                    }else if(c2=='G'){
                                        s1=7;
                                    }else if(c2=='H'){
                                        s1=8;
                                    }else if(c2=='I'){
                                        s1=9;
                                    }else if(c2=='J'){
                                        s1=10;
                                    }else if(c2=='K'){
                                        s1=11;
                                    }else if(c2=='L'){
                                        s1=12;
                                    }else if(c2=='M'){
                                        s1=13;
                                    }else if(c2=='N'){
                                        s1=14;
                                    }else if(c2=='O'){
                                        s1=15;
                                    }else if(c2=='P'){
                                        s1=16;
                                    }else if(c2=='Q'){
                                        s1=17;
                                    }else if(c2=='R'){
                                        s1=18;
                                    }else if(c2=='S'){
                                        s1=19;
                                    }else if(c2=='T'){
                                        s1=20;
                                    }else if(c2=='U'){
                                        s1=21;
                                    }else if(c2=='V'){
                                        s1=22;
                                    }else if(c2=='W'){
                                        s1=23;
                                    }else if(c2=='X'){
                                        s1=24;
                                    }else if(c2=='Y'){
                                        s1=25;
                                    }else if(c2=='Z'){
                                        s1=26;
                                    }else{
                                       s1=0;
                                    }
                    System.out.println("s1 :"+s1);
                       cal2=cal2+s1;
                          System.out.println("cal2 :"+cal2);
                            }
                        char[] ch3 = new char[text3.length()];
                          // Copy character by character into array
                        for (int i2 = 0; i2 < text3.length(); i2++) {
                                ch3[i2] = text3.charAt(i2);
                            }
                         // Printing content of array
                        for (char c3 : ch3) {
                                System.out.println(c3);
                                if(c3=='A'){
                                        s2=1;
                                    }else if(c3=='B'){
                                        s2=2;
                                    }else if(c3=='C'){
                                        s2=3;
                                    }else if(c3=='D'){
                                        s2=4;
                                    }else if(c3=='E'){
                                        s2=5;
                                    }else if(c3=='F'){
                                        s2=6;
                                    }else if(c3=='G'){
                                        s2=7;
                                    }else if(c3=='H'){
                                        s2=8;
                                    }else if(c3=='I'){
                                        s2=9;
                                    }else if(c3=='J'){
                                        s2=10;
                                    }else if(c3=='K'){
                                        s2=11;
                                    }else if(c3=='L'){
                                        s2=12;
                                    }else if(c3=='M'){
                                        s2=13;
                                    }else if(c3=='N'){
                                        s2=14;
                                    }else if(c3=='O'){
                                        s2=15;
                                    }else if(c3=='P'){
                                        s2=16;
                                    }else if(c3=='Q'){
                                        s2=17;
                                    }else if(c3=='R'){
                                        s2=18;
                                    }else if(c3=='S'){
                                        s2=19;
                                    }else if(c3=='T'){
                                        s2=20;
                                    }else if(c3=='U'){
                                        s2=21;
                                    }else if(c3=='V'){
                                        s2=22;
                                    }else if(c3=='W'){
                                        s2=23;
                                    }else if(c3=='X'){
                                        s2=24;
                                    }else if(c3=='Y'){
                                        s2=25;
                                    }else if(c3=='Z'){
                                        s2=26;
                                    }else{
                                       s2=0;
                                    }
                                System.out.println("s2 :"+s2);
                                cal3=cal3+s2;
                                   System.out.println("cal3 :"+cal3);
                            }
                             String v11=cal1+"",v12=cal2+"",v13=cal3+"";
                       jLabel3.setText(v11);  jLabel13.setText(v12); jLabel15.setText(v13);
                               bn=st.executeUpdate("insert into register values('"+jTextField1.getText()+"','"+jComboBox1.getSelectedItem()+"','"+jPasswordField2.getText()+"','"+jPasswordField3.getText()+"','"+jPasswordField4.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+v111+"','"+v112+"','"+v113+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"','"+jTextField7.getText()+"','"+v11+"','"+v12+"','"+v13+"','Active','5000','"+jTextField8.getText()+"','')");
            bn=st.executeUpdate("insert into secure values('"+jTextField1.getText()+"','0','0','0')");
            if(bn==1){
                this.setVisible(false);
                JOptionPane.showMessageDialog(null,"Added Successfully");
                Home rs=new Home();
                rs.setVisible(true);

            }else{
                this.setVisible(true);
                JOptionPane.showMessageDialog(null,"Added Failed");
            }
                       }else{
                          JOptionPane.showMessageDialog(null,"Please select the operation Type");
                       }
                   if((jTextField3.getText().length()<0)&&(jTextField4.getText().length()<0)){
                         JOptionPane.showMessageDialog(null,"enter all character");
                           }else if((jTextField3.getText().length()==3)&&(jTextField4.getText().length()==3)){
                
                           }
        }catch(Exception ex){
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
           this.setVisible(false);
            Register rs11=new Register();
                rs11.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       JFileChooser fc=new JFileChooser();    
    int i=fc.showOpenDialog(this);    
    if(i==JFileChooser.APPROVE_OPTION){    
        File f=fc.getSelectedFile();    
        String filepath=f.getPath();    
        try{  
//        BufferedReader br=new BufferedReader(new FileReader(filepath));    
//        String s1="",s2="";                         
//        while((s1=br.readLine())!=null){    
//        s2+=s1+"\n";    
//        }    
        jTextField9.setText(filepath);    
////        br.close();    
        }catch (Exception ex) {ex.printStackTrace();  }                 
    }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
     
    
    
    }//GEN-LAST:event_jButton3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
